### PR TITLE
Add Projects and Jobs for myself

### PR DESCRIPTION
**Pull request by mdiluz**
This needed a little bit of adjustment to display the project images correctly, let me know if that should be using breakpoints or something instead of `auto`.

### CODE REVIEW

**Comment by mdiluz** [comment]
Tried using GH desktop to do this from Windows and oh boy has it done a weird. I'll fix the PR and rebase it to your upstream/deploy when I get to a Linux box :)

**Comment by mdiluz** [comment]
Sorry about the branch neatness, if you want me to rebase rather than merge let me know

**Comment by T0TProduction** [comment]
No worries, I will squash merge the PR in the end so the history doesn't matter 👌🏻

I'll take a closer look at the PR later (currently on mobile), but from what I saw I think images should be in subfolders, so e.g. static/profile/marc/image.png

**Comment by mdiluz** [comment]
My god Github Desktop does some weird shit to branches. That's the last time I try and do this from Windows haha.

OK cool moved the images down.

**Comment by mdiluz** [comment]
@T0TProduction Somewhat inexplicably the images don't work on the live site. They work locally with `npm run dev` though. Looks like the live site is looking at `marc/profile/marc/unity.png` and the dev site is looking at `profile/marc/unity.png`.

**Comment by T0TProduction** [comment]
That's weird, because for me the live site is loading the images correctly

**Comment by mdiluz** [comment]
Looks like some node behaviour, navigating directly to https://diluz.io/marc has broken images, navigating from https://diluz.io/ is fine

**Comment by T0TProduction** [comment]
Seems like this is the issue we're running into: https://blog.lichter.io/posts/dynamic-images-vue-nuxt/#the-solution

On a side note, to make this possible all images that are used within pages should be moved to assets, as static should not be used for that. 
Makes sense, now that I see this, wasn't fully aware of it before tbh.

**Comment by T0TProduction** [comment]
https://github.com/T0TProduction/diluz.io/pull/50
hoping this fixes is, waiting for the PR preview from netlify

**Pull request merged**
