### PR TITLE
Add myself

### PR DESCRIPTION
**Pull request by mdiluz**
Just some basic info for now, I'll fill in some more later once we know it didn't blow anything up.

Bonus: Add `workflow_dispatch` so the GitHub Action can be manually triggered. Not sure if this'll be needed since it runs on all push events anyway, but I find it better to have it enabled before the need arises.

### CODE REVIEW

**Comment by mdiluz** [comment]
Not sure why the actions aren't running, they're green on my fork. Any ideas?

**Comment by T0TProduction** [comment]
I think they're not running because it's a PR from a fork and not directly within this repo. That way it would theoretically be unsafe to just run (potentially newly added) actions that could send secrets somewhere.
I'll see if I can trigger it manually.

The netlify preview worked though, so that's good.
Noticing two things we might want to fix before merging: 
- there's no button to get to your profile from the main page. I guess I didn't build that to add buttons dynamically, so you could just add one for yourself if you want to
- the dates from your degrees is 1/1970, I guess you need to specify months as well when creating a new date

**Comment by T0TProduction** [comment]
@mdiluz did you see my response? 
No stress, just not sure about your notification settings

**Comment by mdiluz** [comment]
I did, and then promptly forgot! I'll get to this tomorrow

**Comment by mdiluz** [comment]
Those two should be resolved :)

**Comment by mdiluz** [comment]
How hard do you think it'd be to set up some of the verification actions on my fork? I've not used netlify before so don't know how involved it is.

**Comment by mdiluz** [comment]
Looks like I should probably also add some job info there too, I'll get that sorted as well.

**Comment by T0TProduction** [comment]
> How hard do you think it'd be to set up some of the verification actions on my fork? I've not used netlify before so don't know how involved it is.

Should be super easy. I think you only need to connect the repo / branch you want to deploy and then it's ready to go.
For the PRs you'll have a deployment from my netfliy anyways, so it really depends on what you want in addition to that though.

**Comment by T0TProduction** [comment]
> Those two should be resolved :)

The home buttons are a bit close, maybe add some margin there? 
Other than that, looking good!

**Comment by mdiluz** [comment]
OK, should be a little neater now, how about this?

image

**Comment by T0TProduction** [comment]
Lookin good!
I think in the future these buttons should be automatically created from the profiles, but for now this is nice

**Comment by mdiluz** [comment]
Maybe by then I'll have learnt Node!

**Pull request merged**
